language: node_js
node_js:
  - "stable"

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: 
        - cd frontend
        - npm test
      script: 
        - cd backend
        - npm test