language: node_js
node_js:
  - "stable"
before_install:
  - cd backend
install:
  - npm install

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: 
        - cd frontend
        - npm test
      before_script:
        - cd ..
      script: 
        - cd backend
        - npm test